import 'dotenv/config';
import MenuModel from '../infrastructure/database/models/MenuModel';
import connectDB from '../infrastructure/database/config/database';

// Datos de menús a insertar
const menusData = [
  {
    "id": 2,
    "title": "Home",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": null,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 3,
    "title": "Collection",
    "sort": 1,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 1,
    "mega_menu_type": "product_box",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": null,
    "created_by_id": 1,
    "product_ids": [10, 290],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 4,
    "title": "Collection Layouts",
    "sort": 0,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 3,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 6,
    "title": "Collection Left Sidebar",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_left_sidebar",
    "badge_text": "Hot",
    "badge_color": "bg-danger",
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 4,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 8,
    "title": "Collection Right Sidebar",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/collections?layout=collection_right_sidebar",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 4,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 9,
    "title": "Collection No Sidebar",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_no_sidebar",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 4,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 12,
    "title": "Collection 2 grid",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_2_grid",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 4,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 10,
    "title": "Collection 3 Grid",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "collections?layout=collection_3_grid",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 4,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 11,
    "title": "Collection 4 Grid",
    "sort": 5,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_4_grid",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 4,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 13,
    "title": "Collection list",
    "sort": 6,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_list_view",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 4,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 5,
    "title": "Collection Layouts",
    "sort": 1,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 3,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 15,
    "title": "Collection Category Slider",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_category_slider",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 5,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 16,
    "title": "Collection Category Sidebar",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_category_sidebar",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 5,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 14,
    "title": "Collection Top Filter",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_top_filter",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 5,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 17,
    "title": "Collection Sidebar Popup",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/collections?layout=collection_sidebar_popup",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 5,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 56,
    "title": "Infinite Scroll",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/collections?layout=collection_product_infinite_scroll",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 5,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 19,
    "title": "Product",
    "sort": 2,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 1,
    "mega_menu_type": "side_banner",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": 3897,
    "set_page_link": null,
    "parent_id": null,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 20,
    "title": "Product Page",
    "sort": 0,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 19,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 21,
    "title": "Product Thumbnail",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/gym-coords-set?layout=product_thumbnail",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 20,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 22,
    "title": "Product Images",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/gym-coords-set?layout=product_images",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 20,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 23,
    "title": "Product Slider",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/gym-coords-set?layout=product_slider",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 20,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 25,
    "title": "Product Accordion",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/gym-coords-set?layout=product_accordion",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 20,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 24,
    "title": "Product Sticky",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/gym-coords-set?layout=product_sticky",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 20,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 30,
    "title": "Product Vertical Tab",
    "sort": 5,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/gym-coords-set?layout=vertical_tab",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 20,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 36,
    "title": "Product Page",
    "sort": 1,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 19,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 28,
    "title": "Product Sidebar Left",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/gym-coords-set?layout=product_sidebar_left",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 36,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 27,
    "title": "Product Sidebar Right",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/gym-coords-set?layout=product_sidebar_right",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 36,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 26,
    "title": "Product No Sidebar",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/gym-coords-set?layout=product_no_sidebar",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 36,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 31,
    "title": "Product Column Thumbnail",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/gym-coords-set?layout=product_column_thumbnail",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 36,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 29,
    "title": "Product Thumbnail Image Outside",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/gym-coords-set?layout=product_thumbnail_image_outside",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 36,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 37,
    "title": "Product Variants Style",
    "sort": 2,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 19,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 38,
    "title": "Variant Rectangle",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/apple-iphone-14-pro-max",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 37,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 39,
    "title": "Variant Circle",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/scarlet-stunner",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 37,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 40,
    "title": "Variant Image Swatch",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/fitted-coords-set-2",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 37,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 41,
    "title": "Variant Color",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/chic-crop-top",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 37,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 42,
    "title": "Variant Radio Button",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/blue-solid-lightly-padded-antibacterial-t-shirt-bra",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 37,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 43,
    "title": "Variant Dropdown",
    "sort": 5,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/dior-j-adore",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 37,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 102,
    "title": "Product Features",
    "sort": 3,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 19,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 107,
    "title": "Product Simple",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/stripped-bodycon-dress",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 102,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 108,
    "title": "Product Classified",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/fitted-coords-set",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 102,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 103,
    "title": "Size Chart",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/boyfriend-shirts",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 102,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 104,
    "title": "Delivery & Return",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/classic-jacket",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 102,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 105,
    "title": "Product Review",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/versatile-shacket",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 102,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 106,
    "title": "Ask an Expert",
    "sort": 5,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/chic-mini-dress",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 102,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 109,
    "title": "Product Features",
    "sort": 4,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 19,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 110,
    "title": "Bundle (Cross Sale)",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/macbook-pro",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 109,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 111,
    "title": "Hot Stock Progress",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/wooden-diwan",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 109,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 112,
    "title": "Out Stock",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/product/oppo-reno-pro",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 109,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 113,
    "title": "Sale Countdown",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/boyfriend-shirts",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 109,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 114,
    "title": "Product Zoom",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/cumulus-sneakers",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 109,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 115,
    "title": "Product Features",
    "sort": 5,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 19,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 116,
    "title": "Sticky Checkout",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/heart-necklace",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 115,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 117,
    "title": "Secure Checkout",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/ray-ban-eye-glasses",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 115,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 118,
    "title": "Social Share",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/black-gym-suit",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 115,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 119,
    "title": "Related Products",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/blue-solid-lightly-padded-antibacterial-t-shirt-bra",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 115,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 120,
    "title": "Wishlist & Compare",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/product/eco-palm-branch",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 115,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 32,
    "title": "Mega Menu",
    "sort": 3,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 1,
    "mega_menu_type": "bottom_banner",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": 3153,
    "set_page_link": null,
    "parent_id": null,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 85,
    "title": "Top Brands",
    "sort": 0,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 32,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 87,
    "title": "Sunsetglide Surfboards",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/brand/sunsetglide-surfboards",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 85,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 90,
    "title": "Enigma Fragrance",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/brand/enigma-fragrance",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 85,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 86,
    "title": "Driveline Depot",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/brand/driveline-depot",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 85,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 89,
    "title": "Digital Haven",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/brand/digital-haven",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 85,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 88,
    "title": "Lenscrafted",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/brand/lenscrafted",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 85,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 76,
    "title": "Popular Categories",
    "sort": 1,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 32,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 80,
    "title": "Fashion",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/category/fashion",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 76,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 81,
    "title": "Fitgear",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/category/fit-gear-central",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 76,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 82,
    "title": "Lingerie",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/category/lingerie",
    "badge_text": "Hot",
    "badge_color": "bg-warning",
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 76,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 83,
    "title": "Bag",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/category/bag-emporium",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 76,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 84,
    "title": "Watch",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/category/time-sphere",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 76,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 78,
    "title": "Email Template",
    "sort": 2,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 32,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 97,
    "title": "Welcome",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "https://themes.pixelstrap.com/multikart/email-template/welcome.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 78,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 98,
    "title": "Abandonment",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "https://themes.pixelstrap.com/multikart/email-template/abandonment-email.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 78,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 100,
    "title": "Offer Template",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "https://themes.pixelstrap.com/fastkart/email-templete/offer-template.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 78,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 99,
    "title": "Order Success",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "https://themes.pixelstrap.com/multikart/email-template/email-order-success.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 78,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 101,
    "title": "Review",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "https://themes.pixelstrap.com/multikart/email-template/product-review.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 78,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 79,
    "title": "Email Template",
    "sort": 3,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 32,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 92,
    "title": "Announcement",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "https://themes.pixelstrap.com/multikart/email-template/new-product-announcement.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 79,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 93,
    "title": "Flash-sale",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "https://themes.pixelstrap.com/multikart/email-template/flash-sale.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 79,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 94,
    "title": "Black Friday",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "https://themes.pixelstrap.com/multikart/email-template/black-friday.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 79,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 95,
    "title": "Christmas",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "https://themes.pixelstrap.com/multikart/email-template/christmas.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 79,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 96,
    "title": "Cyber Monday",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 1,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "https://themes.pixelstrap.com/multikart/email-template/cyber-monday.html",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 79,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 50,
    "title": "Blogs",
    "sort": 4,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 1,
    "mega_menu_type": "blog_box",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": null,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [1, 2],
    "status": 1
  },
  {
    "id": 53,
    "title": "Blog Page",
    "sort": 0,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 50,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 54,
    "title": "Grid Left Sidebar",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "blogs?style=grid_view&sidebar=left_sidebar",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 53,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 52,
    "title": "Grid Right Sidebar",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "blogs?style=grid_view&sidebar=right_sidebar",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 53,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 55,
    "title": "Grid No Sidebar",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "blogs?style=grid_view&sidebar=no_sidebar",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 53,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 51,
    "title": "Blog List",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "blogs?style=list_view&sidebar=left_sidebar",
    "badge_text": "New",
    "badge_color": "bg-danger",
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 53,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 57,
    "title": "Pages",
    "sort": 5,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": null,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 58,
    "title": "Account",
    "sort": 0,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 59,
    "title": "My Dashboard",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/account/dashboard",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 58,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 60,
    "title": "My Notifications",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/account/notifications",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 58,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 61,
    "title": "Bank Details",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/account/bank-details",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 58,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 62,
    "title": "My Wallet",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/account/wallet",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 58,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 63,
    "title": "My point",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "account/point",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 58,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 64,
    "title": "My Order",
    "sort": 5,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/account/order",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 58,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 65,
    "title": "Refund History",
    "sort": 6,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/account/refund",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 58,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 66,
    "title": "About Us",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/about-us",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 67,
    "title": "Browse FAQs",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/faq",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 68,
    "title": "Cart",
    "sort": 3,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/cart",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 72,
    "title": "Offers",
    "sort": 4,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/offers",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 71,
    "title": "Contact Us",
    "sort": 5,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/contact-us",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 70,
    "title": "Compare",
    "sort": 6,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/compare",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 69,
    "title": "Checkout",
    "sort": 7,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/checkout",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 73,
    "title": "Search",
    "sort": 8,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/search",
    "badge_text": "Hot",
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 74,
    "title": "Wishlist",
    "sort": 9,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/wishlist",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 75,
    "title": "404",
    "sort": 10,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/404",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 57,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 44,
    "title": "Seller",
    "sort": 6,
    "link_type": "sub",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": null,
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": null,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 45,
    "title": "Become Seller",
    "sort": 0,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/seller/become-seller",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 44,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 46,
    "title": "Seller Stores",
    "sort": 1,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": "simple",
    "path": "/seller/stores",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 44,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  },
  {
    "id": 47,
    "title": "Store Details",
    "sort": 2,
    "link_type": "link",
    "is_target_blank": 0,
    "mega_menu": 0,
    "mega_menu_type": null,
    "path": "/seller/store/bag-emporium",
    "badge_text": null,
    "badge_color": null,
    "item_image_id": null,
    "banner_image_id": null,
    "set_page_link": null,
    "parent_id": 44,
    "created_by_id": 1,
    "product_ids": [],
    "blog_ids": [],
    "status": 1
  }
];

async function loadMenus() {
  await connectDB();
  console.log('✅ Conectado a MongoDB');

  try {
    // Limpiar menús existentes (opcional - comentar si no quieres eliminar los existentes)
    console.log('🗑️ Limpiando menús existentes...');
    await MenuModel.deleteMany({});
    console.log('   ✅ Menús existentes eliminados');

    // Ordenar menús: primero los que no tienen parent_id, luego los hijos
    const sortedMenus = [...menusData].sort((a, b) => {
      // Si uno tiene parent_id y el otro no, el que no tiene parent_id va primero
      if (a.parent_id === null && b.parent_id !== null) return -1;
      if (a.parent_id !== null && b.parent_id === null) return 1;
      // Si ambos tienen o no tienen parent_id, ordenar por id
      return a.id - b.id;
    });

    console.log(`📊 Total de menús a insertar: ${sortedMenus.length}`);

    // Insertar menús
    let insertedCount = 0;
    for (const menuData of sortedMenus) {
      try {
        // Normalizar valores
        const menuToInsert: any = {
          id: menuData.id,
          title: menuData.title,
          link_type: menuData.link_type,
          path: menuData.path || undefined,
          parent_id: menuData.parent_id === null ? null : menuData.parent_id,
          sort: menuData.sort,
          mega_menu: menuData.mega_menu,
          mega_menu_type: menuData.mega_menu_type || undefined,
          set_page_link: menuData.set_page_link || undefined,
          badge_text: menuData.badge_text || undefined,
          badge_color: menuData.badge_color || undefined,
          is_target_blank: menuData.is_target_blank,
          product_ids: menuData.product_ids || [],
          blog_ids: menuData.blog_ids || [],
          banner_image_id: menuData.banner_image_id || null,
          item_image_id: menuData.item_image_id || null,
          status: menuData.status,
          created_by_id: menuData.created_by_id
        };

        const menu = new MenuModel(menuToInsert);
        await menu.save();
        insertedCount++;
        console.log(`   ✅ Menú insertado: ${menuData.title} (ID: ${menuData.id})`);
      } catch (error: any) {
        console.error(`   ❌ Error insertando menú ${menuData.title} (ID: ${menuData.id}):`, error.message);
      }
    }

    console.log(`\n✅ Proceso completado: ${insertedCount}/${sortedMenus.length} menús insertados exitosamente`);
    process.exit(0);
  } catch (error: any) {
    console.error('❌ Error durante la carga de menús:', error);
    process.exit(1);
  }
}

loadMenus();
